# Generated by Django 6.0.1 on 2026-01-07 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('exchange_rate', models.FloatField()),
                ('base_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.currency')),
            ],
        ),
    ]
