# Generated by Django 6.0.1 on 2026-01-07 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.currency'),
        ),
    ]
