# Generated by Django 6.0.1 on 2026-01-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='account_type',
            field=models.IntegerField(default=0),
        ),
    ]
