# Generated by Django 6.0.1 on 2026-02-14 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_currency_base_currency'),
        ('wallets', '0002_wallet_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='account_type',
            field=models.IntegerField(choices=[(0, 'Saving'), (1, 'Checking')], default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.currency'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_code',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
